// <auto-generated />
using System;
using BethanysPieShopAdmin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BethanysPieShopAdmin.Migrations
{
    [DbContext(typeof(TreningDbContext))]
    partial class TreningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BethanysPieShopAdmin.Data.Models.Trening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Treninzi", (string)null);
                });

            modelBuilder.Entity("BethanysPieShopAdmin.Data.Models.Vezba", b =>
                {
                    b.Property<int>("VezbaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VezbaId"), 1L, 1);

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("Rekviziti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TreningId")
                        .HasColumnType("int");

                    b.Property<string>("VezbaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VezbaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VezbaId");

                    b.HasIndex("TreningId");

                    b.ToTable("Vezbe", (string)null);
                });

            modelBuilder.Entity("BethanysPieShopAdmin.Data.Models.Vezba", b =>
                {
                    b.HasOne("BethanysPieShopAdmin.Data.Models.Trening", "Trening")
                        .WithMany("Vezbas")
                        .HasForeignKey("TreningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trening");
                });

            modelBuilder.Entity("BethanysPieShopAdmin.Data.Models.Trening", b =>
                {
                    b.Navigation("Vezbas");
                });
#pragma warning restore 612, 618
        }
    }
}
